image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

services:
- name: docker:20.10.16-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

stages:
- build
- test
- visualize

build:
  stage: build
  script:
    - mvn -s settings.xml --show-version Dmaven.test.skip=true clean install