package mx.edu.itspa.esgi.scse.model;

public enum Departments {
	DIVISION_GESTION_EMPRESARIAL("DIVISIÓN DE INGENIERÍA EN GESTIÓN EMPRESARIAL"), 
	DIVISION_ADMINISTRACION("DIVISIÓN DE INGENIERÍA EN ADMINISTRACIÓN"),
	DIVISION_DESARROLLO_COMUNITARIO("DIVISIÓN DE INGENIERÍA EN DESARROLLO COMUNITARIO"), 
	DIVISION_AMBIENTAL("DIVISIÓN DE INGENIERÍA AMBIENTAL"),
	DIVISION_TICS("DIVISIÓN DE INGENIERÍA EN TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIONES"), 
	DIVISION_BIOMEDICA("DIVISIÓN DE INGENIERÍA BIOMÉDICA");

	private final String value;

	Departments(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
}
